#!/bin/bash

sudo apt-get remove docker docker-engine docker.io

sleep 1

sudo apt-get update

sleep 1

sudo apt-get install apt-transport-https ca-certificates curl software-properties-common

sleep 1

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sleep 3

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sleep 3

sudo apt-get update

sleep 1

sudo apt-get install docker-ce

